sudo: required
language: go
go:
- '1.11'
go_import_path: github.com/xiaokangwang/AndroidLibV2ray
git:
  depth: 5
addons:
  apt:
    update: true
before_script:
- sudo ntpdate -u time.google.com
- date
- make all
- make downloadGoMobile
script:
- go test -p 1 -tags json -v github.com/xiaokangwang/AndroidLibV2ray/...
- make BuildMobile
after_success:
deploy:
  provider: releases
  api_key:
    secure: KUgrAxQsfZW2tFEoIzWmwD9npGwOWr+lXoEocYliAF8PWz+mlZbjqfXfISmHfZ7nbqUebRcxsz/kP3M6Q5YLIGHi3k/nziLiXYPp/qY33ipYDeaxoH0Ho/2fCTI/fewzrg4ZtIfiuhvoP8c2tJvuFyFZWZ7zLgnh/fnqWi05IX+cjd+aGx1hCPugiwCEKBK5YCYwPV9KOHRwIdz7f3iotfVR8OFfauiy+0imYAkPehcMNHVDK7H8oRmPXEwZdKXVzzjjRKOLdQykotzNfqPJpLFvGb4gWx2OcZk/wSn6lwooknjya8KhQF26LDCgGayVZFbt5EmT8YbVCE9PJ68/UKVL4PZxrYJXd665bkOcSHr8u05cXJ7prBRcW5z7z2dFnIxraxRi1rEZ1zw8oD6nSiFm7mQBd/lAg2sTjJZZ7Lm8zBzDZQb72tJjXrZRQ9nnUcBpVcUfgoAeS1QY5pOYZRsEqIPD4vnv5258DchkZoRoh4ofBY2HVNKNEn6SuC0SsVd65FvO/ZSkHdGWTBnImDKPKXyo6mjp6Oc7pq8ZvwpCtmKOZJK7rZprd8v80O0SIRhZtNm7gIz2VlqXu71WOJXk0MSChYJ1lryyOr8eaNLg9A/LbSaM/3dM5hw3qOzIVdpuFsSgf+4QsUOIiXt4etMCHh/RwSnHb1pFScyvWEY=
  file:
    - libv2ray.aar
  skip_cleanup: true
  on:
    tags: true
    repo: TachibanaTech/AndroidLibV2ray
